#! /usr/bin/env ruby

require 'optparse'

options = { :file => nil }

parser = OptionParser.new do |opts|
  opts.banner = "Usage: file_batch_users [options]"
  opts.on('-f', '--file FILE', 'File') do |file|
    options[:file] = file
  end
end

parser.parse!

unless options[:file].nil?
  file_path = options[:file]

  unless File.exists?(file_path)
    puts "File not exists."
    exit(1)
  end

  lines = File.readlines(file_path)
  users = lines.map do |line|
    line.split(/\ |,|;/).map { |u| u.strip }
  end.flatten.select { |user| !user.empty? }

  users.each do |user|
    syscall = `useradd --password #{user.reverse.crypt("aMAGICpwd")} #{user}`
    puts syscall ? "#{user} created" : "#{user} failed"
  end
end

